name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:

  codeql:
    name: Code Scan
    runs-on: ubuntu-latest
    if: github.event.repository.visibility == 'public'
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialise CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python
      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

  pip-audit:
    name: Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run Dependency Scan
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: app/requirements.txt

  pytest:
    name: Pytest
    needs: [codeql, pip-audit]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: pip install -r app/requirements.txt
      - name: Run Tests
        run: pytest

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [codeql, pip-audit, pytest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t secure-devsecops-release-platform:${{ github.sha }} .

      - name: Save Image
        run: docker save secure-devsecops-release-platform:${{ github.sha }} -o secure-devsecops-release-platform-image.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: secure-devsecops-release-platform-image.tar
          retention-days: 1

  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: High Severity Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          input: secure-devsecops-release-platform-image.tar
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          trivy-version: 'latest'

      - name: Low Severity Scan
        if: always()
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          input: secure-devsecops-release-platform-image.tar
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'MEDIUM'
          trivy-version: 'latest'

  push-image:
    name: Push Image to GHCR
    runs-on: ubuntu-latest
    needs: [docker-build, trivy-scan]
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Image
        run: docker load -i secure-devsecops-release-platform-image.tar

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image
        run: |
          docker tag secure-devsecops-release-platform:${{ github.sha }} ghcr.io/yashjagani17/secure-devsecops-release-platform:${{ github.sha }}
          docker tag secure-devsecops-release-platform:${{ github.sha }} ghcr.io/yashjagani17/secure-devsecops-release-platform:latest

      - name: Push image
        run: |
          docker push ghcr.io/yashjagani17/secure-devsecops-release-platform:${{ github.sha }}
          docker push ghcr.io/yashjagani17/secure-devsecops-release-platform:latest